---

wiki_app_fqdn: "INSERT_FQDN"

m_private_networking_zone: "public"

# Password for mysql root user
mysql_root_password: "1234"

wiki_app_db_user:
  name: "wiki_app_user"
  password: "1234"
  priv: "*.*:ALL"

# List of users. Currently only wiki_app_user is required. This should perhaps
# be handled in such a way that it's not possible to remove wiki_app_user, and
# then this mysql_users list would just be for additional users (e.g. humans
# who want to query the database). Alternatively, this would be easy to create
# separate users for each wiki (which I've heard can have performance benefits)
mysql_users: []
  # - name: "james"
  #   host: "%"
  #   password: "mypassword"
  #   priv: "*.*:ALL"

# User on database master that slaves use perform replication
mysql_replication_user:
  name: "db_slave_user"
  password: "1234"

# Do you want your wiki to be able to email?
# must be either:
#   true
#   false
enable_wiki_emails: true

# May be required for certain cryptographic functions
wg_secret_key: TjahGKHrcnqGwX0nyMwWkvTfpfReRphMZUR7EkWzKC8YmR6yZ9zPCse24MPGWX39
